try {
  console.log("oops")
} catch (error) {
  console.error(error.message)
}